import {useState, type FormEvent} from 'react';
import {Check, Minus, Plus, ArrowRight} from 'lucide-react';
import {Action, Night, countdown, LAST_OFFER, PICKUP, stats, timeLabel, waiting} from '../model';

export function Merchant({night:n,act}:{night:Night;act:(a:Action)=>void}) {
  const s=stats(n);const [code,setCode]=useState('');const [message,setMessage]=useState('');
  const collecting=n.phase==='collecting';const closed=n.phase==='closed';
  const shortage=!collecting&&s.available>0;
  const verify=(e:FormEvent)=>{e.preventDefault();const g=n.guests.find(g=>g.code===code.trim()&&g.status==='reserved');if(!g){setMessage('No active reservation matches that code.');return;}if(n.now<PICKUP){setMessage('Pickup opens at 7:30 PM.');return;}act({type:'PICKUP',id:g.id});setCode('');setMessage(`Bag ${g.bag} collected. $5 received (demo).`);};
  return <section className="merchant-layout">
    <div className="merchant-heading"><p>Wednesday, September {n.day} · Demo evening</p><h1 tabIndex={-1}>{collecting?'A good end to the day.':closed?'Every bag, accounted for.':'Done. We’ll handle the rest.'}</h1><p className="intro">{collecting?'Count what’s left. We’ll take it from here.':closed?'Tonight’s results, from confirmed bags to completed pickups.':`${n.confirmed} bags confirmed. Offers and reassignment are running automatically.`}</p></div>
    {collecting?<>
      <div className="count-layout"><div className="count-workspace"><h2>How many bags are ready?</h2><div className="quantity-control"><button aria-label="Decrease bag count" disabled={n.quantity===0} onClick={()=>act({type:'QUANTITY',value:n.quantity-1})}><Minus/></button><output aria-live="polite" aria-label="Bag quantity">{n.quantity}</output><button aria-label="Increase bag count" disabled={n.quantity===12} onClick={()=>act({type:'QUANTITY',value:n.quantity+1})}><Plus/></button></div><p className="count-details">$5 per bag · Pickup 7:30–8:00 PM</p><button className="primary" onClick={()=>act({type:'CONFIRM'})}>{n.quantity===0?'Confirm no surplus':`Confirm ${n.quantity} ${n.quantity===1?'bag':'bags'}`}<ArrowRight size={19}/></button><small className="button-note">Only confirm bags you’ve counted and packed.</small>{n.now>LAST_OFFER&&<p className="caution">New offers stopped at 7:45 PM. You can record surplus, but these bags cannot be allocated tonight.</p>}</div>
      <aside className="tonight-aside"><h2>Tonight, at a glance</h2><div className="fact-row"><strong>{waiting(n).length}</strong><span>people interested</span></div><div className="fact-row"><strong>0</strong><span>bags promised</span></div><div className="fact-row"><b>7:30–8:00 PM</b><span>pickup</span></div><p>One confirmation. Timed offers and reassignment run automatically.</p></aside></div>
      <section className="after-confirm"><h2>After you confirm</h2><div className="explanation-columns"><div><h3>Offer to the queue</h3><p>Five-minute offers, in transparent priority order.</p></div><div><h3>Keep bags moving</h3><p>Declined or expired offers go to the next guest, while time allows.</p></div><div><h3>Track every pickup</h3><p>Verify a pickup code at handover. The results update themselves.</p></div></div></section>
    </>:<>
      <div className="merchant-impact"><div><Check size={18}/><strong>{n.confirmations} inventory confirmation</strong><span>Allocation handled automatically</span></div><small>{n.pickups} pickup {n.pickups===1?'checkoff':'checkoffs'} · Counting, packing and handover still take staff time</small></div>
      {closed?<Results night={n}/>:<>
        <div className="live-summary"><div><strong>{s.held}</strong><span>live offers</span></div><div><strong>{s.reserved}</strong><span>reserved</span></div><div><strong>{s.picked}</strong><span>picked up</span></div><div><strong>{s.available}</strong><span>unallocated</span></div></div>
        {shortage&&<div className="honest-note"><h3>{n.now>LAST_OFFER?'Too little pickup time to offer again.':waiting(n).length===0?'Waitlist exhausted.':'Waiting for eligible guests.'}</h3><p>{s.claimed} of {n.confirmed} claimed · {s.available} {s.available===1?'bag has':'bags have'} no active offer. {n.now>LAST_OFFER?'We leave five minutes to respond and ten to arrive.':'The system can distribute bags, but it can’t create demand.'}</p></div>}
      </>}
      <div className="operations-grid"><section><div className="section-title"><h2>{closed?'Bag outcomes':'Live bag status'}</h2><span>{n.confirmed} confirmed</span></div><div className="bag-list">{n.bags.length===0?<p className="empty-state">No surplus confirmed. No offers sent, no customer commitments.</p>:n.bags.map(b=>{const g=n.guests.find(g=>g.id===b.guest);const status=b.status==='remaining'?(g?.status==='no-show'?'Missed pickup':'Unclaimed'):b.status==='picked-up'?'Collected':b.status==='reserved'?'Reserved':b.status==='offered'?'Offer pending':'No active offer';return <div className="bag-row" key={b.id}><span className="bag-number">{String(b.id).padStart(2,'0')}</span><div><strong>Bag {b.id}</strong><small>{g?(g.id==='alex'?'Alex · demo consumer':g.label):'Still with the bakery'}</small></div><div className={`bag-status ${b.status}`}><span>{status}</span>{b.status==='offered'&&<small>{countdown(g!.deadline!-n.now)} left</small>}</div></div>;})}</div>
      {!closed&&s.reserved>0&&<form className="pickup-form" onSubmit={verify}><label htmlFor="pickup-code">Verify a pickup</label><p>Match the guest’s code, hand over the bag, and collect $5.</p><div><input id="pickup-code" value={code} onChange={e=>{setCode(e.target.value.replace(/\D/g,'').slice(0,4));setMessage('');}} placeholder="4-digit code" inputMode="numeric" autoComplete="off" pattern="[0-9]{4}" required maxLength={4}/><button className="primary" type="submit" disabled={n.now<PICKUP}>Mark collected</button></div>{n.now<PICKUP&&<small>Pickup opens at 7:30 PM.</small>}<p role="status">{message}</p></form>}
      </section><aside className="activity"><h2>What happened tonight</h2><ol>{n.events.slice().reverse().slice(0,8).map(e=><li key={e.id}><time>{timeLabel(e.time)}</time><p>{e.text}</p></li>)}</ol></aside></div>
      {closed&&<button className="secondary next-night" onClick={()=>act({type:'NEXT_NIGHT'})}>Start the next evening <ArrowRight size={18}/></button>}
    </>}
  </section>;
}
function Results({night:n}:{night:Night}) {
  const s=stats(n);
  return <section className="results" aria-label="Tonight’s demo results"><div className="result-head"><div><p>Recovered at pickup · Demo</p><strong className="revenue">${s.revenue}</strong><p>{s.picked} completed {s.picked===1?'pickup':'pickups'} × $5. No-shows earn no revenue.</p></div><div className="sell-through"><strong>{n.confirmed?`${s.sellThrough}%`:'—'}</strong><p>Confirmed-surplus sell-through</p><small>Completed pickups ÷ confirmed bags</small></div></div><div className="outcome-strip" aria-hidden="true">{n.bags.map(b=><span key={b.id} className={b.status==='picked-up'?'collected':''}/>)}</div><div className="result-counts"><div><strong>{n.confirmed??0}</strong><span>confirmed</span></div><div><strong>{s.claimed}</strong><span>claimed</span></div><div><strong>{s.picked}</strong><span>picked up</span></div><div><strong>{s.remaining}</strong><span>remaining</span></div><div><strong>{s.noShows}</strong><span>missed pickups</span></div></div><p className="result-note">{s.remaining>0?`${s.remaining} ${s.remaining===1?'bag remains':'bags remain'} with the bakery. ${s.noShows>0?'Missed pickups are included in remaining bags. ':''}No late reassignment, no invented sale.`:n.confirmed===0?'No leftover bags tonight. Guests who waited without an offer earn a priority credit.':'Every confirmed bag was collected tonight.'}</p></section>;
}
